### PR TITLE
Create Viper-athene-7.1.2-Python-v2.0-20170615-OFFICIAL_changelog.txt

### PR DESCRIPTION
**Pull request by brunobdantas**

### CODE REVIEW

**Comment by Andersonmendes2016** [comment]
@brunobdantas dilisaaaaaaaaaaaa

**Comment by Andersonmendes2016** [comment]
@brunobdantas tem burn in?

**Comment by brunobdantas** [comment]
Sweeter than sweet potato candy!

**Comment by Andersonmendes2016** [comment]
@brunobdantas ata bls

**Pull request merged**
